HotelProj1/HotelApp/urls.py
from django.conf.urls import url
from . import views
app_name = 'HotelApp'

urlpatterns = [
    url('^$', views.Index.as_view(),name='index'),
    url('^table/$', views.Table.as_view(),name='table'),
    url('^create/$', views.Create.as_view(),name='create'),
    url (r'^table/(?P<pk>\d+)/$',views.Detail.as_view(),name='detail')
]

HotelProj1/HotelProj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('HotelApp.urls',namespace='HotelApp')),

]

HotelProj1/HotelApp/models.py
from django.db import models
from django.urls import reverse


class Manager(models.Model):
    name = models.CharField(max_length=50)
    contact = models.CharField(max_length=25)
    booking = models.CharField(max_length=25)
    def __str__(self):
        return self.booking

class Customer(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    contact = models.CharField(max_length=25)
    address = models.CharField(max_length=50, null=True)
    date = models.DateTimeField()
    booking= models.ForeignKey(Manager,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('HotalApp:index')

HotelProj1/HotelApp/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import *


class Index(TemplateView):
    template_name = 'index.html'

class Table(ListView):
    model = Customer
    template_name = 'table.html'


class Create(CreateView):
    model = Customer
    fields = ('__all__')
    template_name = 'create.html'

class Detail(DetailView):
    model = Customer
    template_name = 'detail.html'

class Delete(DeleteView):
    model = Customer
    template_name = 'delete.html'

HotelProj1/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>The Taj Krishna</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="jumbotron">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'HotelApp:index' %}"><img src="{% static 'images/logo.png' %}"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'HotelApp:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'HotelApp:table' %}">User</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'HotelApp:create' %}">Booking</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'admin:index' %}">Admin</a>
      </li>
    </ul>
      <a href="{% url 'HotelApp:create' %}" ><button type="button" class="btn btn-success">+ Add New</button></a>
  </div>
</nav>






    </div>





</div>
{% block body_block %}



{% endblock %}
</body>
</html>

HotelProj1/templates/create.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<style>

    input,form{
        width: 100%;
    }
</style>
</head>
<body>
<div class="container">
<div class="jumbotron">
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}


    <p><label for="id_id">Id:</label> <input type="text" name="id" maxlength="25" required id="id_id"></p>
    <p><label for="id_name">Name:</label> <input type="text" name="name" maxlength="25" required id="id_name"></p>
    <p><label for="id_age">Age:</label> <input type="text" name="age" maxlength="25" required id="id_age"></p>
    <p><label for="id_contact">Contact:</label> <input type="text" name="contact" maxlength="25" required id="id_contact"></p>
<p><label for="id_address">Address:</label> <input type="text" name="address" maxlength="25" required id="id_address"></p>
<p><label for="id_booking">Bokking:</label> <select name="booking" required id="id_booking">
  <option value="" selected>---------</option>

  <option value="1">Single Bed</option>

  <option value="2">Double Bed</option>

</select></p>
    <input type="hidden" name="csrfmiddlewaretoken" value="Om1ALZA4odK92kdOE2P9BQaq7RUEYHajEay4kSrZsb3puoFS60lw1oqcdQwzpYtq">
    <input type="submit" class="btn btn-info" value="ADD Customer">
    

</form>





</div>




</div>

</body>
{% endblock %}
</html>

HotelProj1/templates/delete.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer Deleted</title>
<style>
    h1{
        text-align: center;
        color: #4CAF50;
    }
</style>
</head>
<body>
<div class="container">
<div class="jumbotron">

<h1><em>Detail of {{ customer.name }}</em></h1><br>
    <em><h3>Customer ID :{{ customer.id}}</h3></em>
    <em><h3>Name :{{ customer.name }}</h3></em>
    <em><h3>Age :{{ customer.age }}</h3></em>
    <em><h3>Contact :{{ customer.contact }}</h3></em>
    <em><h3>Address :{{ customer.address }}</h3></em>
    <em><h3>Booking :{{ customer.booking }}</h3></em>





</div>




</div>

</body>
{% endblock %}
</html>

HotelProj1/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer Details</title>
<style>
    h1{
        text-align: center;
        color: #4CAF50;
    }
</style>
</head>
<body>
<div class="container">
<div class="jumbotron">

<h1><em>Detail of {{ customer.name }}</em></h1><br>
    <em><h3>Customer ID :{{ customer.id}}</h3></em>
    <em><h3>Name :{{ customer.name }}</h3></em>
    <em><h3>Age :{{ customer.age }}</h3></em>
    <em><h3>Contact :{{ customer.contact }}</h3></em>
    <em><h3>Address :{{ customer.address }}</h3></em>
    <em><h3>Booking :{{ customer.booking }}</h3></em>





</div>




</div>

</body>
{% endblock %}
</html>

HotelProj1/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
    {% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>The Taj Krishna</title>


</head>
<body>
<div class="container">
    <div class="jumbotron">
        <br><br>
<div>
    <h1><em><img src="{% static 'images/banner1.jpg' %}" style="width: 1000px" height="500px"></em></h1>
        <h1><em><img src="{% static 'images/image4.jpg' %}" style="width: 500px" height="500px"></em></h1>
</div>
    </div>
</div>
</body>
{% endblock %}
</html>

HotelProj1/templates/other.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
<div class="jumbotron">






</div>




</div>

</body>
{% endblock %}
</html>

HotelProj1/templates/table.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer Info</title>
<style>
    table{
        width: 100%;
    }
    #customers {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#customers td, #customers th {
    border: 1px solid #ddd;
    padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
}
    h1{
        text-align: center;
        color: #4CAF50;
    }
</style>
</head>
<body>
<div class="container">
<div class="jumbotron">
<h1><em>ALL Customer</em></h1><br>



    <table id="customers" border="2">
        <thread>
        <th> ID </th>
        <th> Name</th>
        <th> Contact</th>
        <th> View </th>
        <th> Delete </th>
        </thread>

         {% for x in customer_list %}
             <tr>
             <td>{{ x.id }}</td>
             <td>{{ x.name }}</td>
             <td>{{ x.contact }}</td>
             <td><a href="{{ x.id }}">  View</a></td>
             <td><a href="{{ x.id }}">  Delete This Id</a></td>

</tr>
  {% endfor %}
    </table>




</div>




</div>

</body>

{% endblock %}

</html>